version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12
        environment:
          NPM_CONFIG_COLOR: false
    parallelism: 1
    steps:
      - checkout
      - run: npm install && npm run lint
