version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  test:
    executor:
      name: node/default
      tag: 20.0.0
    steps:
      - checkout
      - run: npm install && npm run lint

workflows:
  test:
    jobs:
      - test
